### PR TITLE
adding down and up mgmt cmd, fixes #29

### LINKED ISSUE #29: Management command to go down and come up again.
Hi @dstegelman 

What do you think about a management command to control the downtime from CI systems? Going down before the deployment starts using 

    python manage.py downtime_start

and then 

    python manage.py downtime_end

to come up  to normal mode. Would you merge this feature?

### PR DESCRIPTION
**Pull request by philippeowagner**

### CODE REVIEW

**Comment by dstegelman** [comment]
Thanks for your contribution.  Could you add some documentation to the usage page in the docs?

**Comment by philippeowagner** [comment]
@dstegelman docs updated

**Comment by philippeowagner** [comment]
Like a pro! ;-) Thanks for pushing a new release to the PyPI!

**Comment by dstegelman** [comment]
:+1:

**Pull request merged**
